---
resources:
- name: src
  type: git
  check_every: 1m
  source:
    uri: https://github.com/MrIqbalSingh/concourse-demos.git
    branch: main

jobs:
- name: whats-here
  plan:
    - get: src
      trigger: true
    - task: list
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: oci-build-task
        params:
         DOCKERFILE: src/Dockerfile
        inputs:
        - name: src
        run:
          path: build
