---
resources:
- name: src
  type: git
  check_every: 1m
  source:
   uri: git@github.com:MrIqbalSingh/concourse-demos.git
   branch: main

jobs:
- name: whats-here
  plan:
  - get: src
  - task: list
    config:
      platform: linux
       image resource:
        type: registry-image
        source:
         repository: alpine
         tag: latest
       inputs:
       - name: src
       run:
        path: /bin/sh
        args:
        - -esc
        - |
        cd src
        ls
